apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/chat-socket-challenge-main-angular-chat-net: "true"
    io.kompose.service: backend
  name: backend
spec:
  containers:
    - env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PASSWORD
          value: devpassword
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          value: devuser
        - name: SPRING_PROFILES_ACTIVE
          value: pdn
      image: gporras/chat-socket-broker:latest
      livenessProbe:
        exec:
          command:
            - curl -m 5 --silent --fail --request GET http://localhost:8080/actuator/health | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
        failureThreshold: 10
        periodSeconds: 10
        timeoutSeconds: 2
      name: backend
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
  restartPolicy: OnFailure

  apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: backend
    action: ALLOW